apiVersion: skaffold/v2beta8
kind: Config
metadata:
  name: ingestion
deploy:
  kubectl:
    manifests:
    - k8s/deployment.yml
build:
  artifacts:
    - image: abstrakten/ingestion
      context: .
      jib: {}