apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion-deployment
spec:
  selector:
    matchLabels:
      app: ingestion
  template:
    metadata:
      labels:
        app: ingestion
    spec:
      containers:
        - name: ingestion
          image: abstrakten/ingestion
          ports:
            - containerPort: 8080