apiVersion: apps/v1
kind: Deployment
metadata:
  name: mushimushi-deployment
spec:
  selector:
    matchLabels:
      app: mushimushi
  template:
    metadata:
      labels:
        app: mushimushi
    spec:
      containers:
        - name: mushimushi
          image: abstrakten/mushimushi
          ports:
            - containerPort: 8080
