spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://${DB_ADDRESS:localhost:5432}/mushimushi
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
    driverClassName: org.postgresql.Driver
